<header class="main-header">
    <!-- Logo -->
    <a href="/admin" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>P</b>bblg</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Princess</b>Bubblegum</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/"><i class="fa fa-external-link"></i> Go to site</a>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    <a href="#">
                        <i class="fa fa-lg fa-user" data-fa-transform="grow-6"></i>&nbsp;
                        <span class="hidden-xs">Alexander Pierce</span>
                    </a>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="/logout">Logout <i class="fa fa-sign-out"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>