<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="<?php if ($this->url('admin-games-list') == $this->url()) echo "active";?>">
                <a href="<?=$this->url('admin-games-list')?>">
                    <i class="fa fa-gamepad"></i> <span>Games</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>