<div class="box-footer clearfix">
    <div style="margin-right: 10px;float:left;">
    <ul class="pagination pagination no-margin">
        <li><a href="#">«</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">»</a></li>
    </ul>
    </div>
    <div style="margin-top: 7px;float:left;">
        View 10 from 333
    </div>
</div>
