<!-- Masthead -->
<header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12 mx-auto">
                <h2 class="mb-5">
                    Это быстрая и азартная карточная игра с элементами блефа, возможностью частично рассчитывать
                    действия противников и весомой долей везения.
                </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                <form>
                    <div class="form-row">
                        <div class="col-12 col-md-12">
                            <a href="/game" class="btn btn-block btn-lg btn-primary">Играть</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

<!-- Testimonials -->
<section class="testim onials text-center bg-light" style="background-color: #a0ceb2 !important;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="img/win-1.jpg" alt="">
                    <h5>Рейтинги</h5>
                    <p class="font-weight-light mb-0">Выигрывай, стань лучшим</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="img/win-2.jpg" alt="">
                    <h5>Матчи</h5>
                    <p class="font-weight-light mb-0">Еженедельные матчи с приятными призами</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <img class="img-fluid rounded-circle mb-3" src="img/win-3.jpg" alt="">
                    <h5>Квесты</h5>
                    <p class="font-weight-light mb-0">Играй каждый день и получай бонусы</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Image Showcases -->
<section class="showcase">
    <div class="container-fluid p-0">
        <div class="row no-gutters">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.png');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text text-al text-right">
                <h2>1 - Парнишка Финн</h2>
                <p class="lead mb-0">Назови карту от 2 до 8, выбери игрока,<br/>
                    если у него есть названная карта он<br/>
                    выбывает из раунда</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-2.png');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <h2>2 - Пес Джейк</h2>
                <p class="lead mb-0">Посмотри карут на руке у другого игрока</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-3.png');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text text-right">
                <h2>3 - БиМо</h2>
                <p class="lead mb-0">В тайне от остальных сравни свою руку <br/>
                    с рукой другого игрока. У кого значение меньше, <br/>
                    тот выбывает из раунда</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-4.png');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <h2>4 - ППК</h2>
                <p class="lead mb-0">До следующего твоего хода <br/>
                    игнорируй все эффекты карт других игроков</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-5.png');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text text-right">
                <h2>5 - Маршал Ли</h2>
                <p class="lead mb-0">Выбери другого игрока (можно себя) <br/>
                    этот игрок сбрасывает карту с руки и берет новую</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-6.png');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <h2>6 - Ледяной король</h2>
                <p class="lead mb-0">Поменяйся картой с руки с другим, <br/>
                    выбранным тобою, игроком </p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-7.png');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text text-right">
                <h2>7 - Марселина</h2>
                <p class="lead mb-0">Если эта карта у тебя на руке одоновременно<br/>
                    с Ледяным королем или Маршалом Ли<br/>
                    ты должен сбросить ее</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-8.png');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <h2>8 - Принцесса жвачка</h2>
                <p class="lead mb-0">Если сбросишь эту карту, тут же выбываешь из раунда</p>
            </div>
        </div>
    </div>
</section>

<!-- Call to Action -->
<section class="call-to-action text-white text-center">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <h2 class="mb-4">Готов?</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto">
                <form>
                    <div class="form-row">
                        <div class="col-12 col-md-12">
                            <a href="/game" class="btn btn-block btn-lg btn-primary">Играть</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>