<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <div class="panel panel-primary mt-5">
                <div class="panel-body">
                    <form method="POST" action="#" role="form">
                        <div class="form-group">
                            <h2>Логин</h2>
                        </div>
                        <div class="form-group">
                            <input id="signupName" type="text" maxlength="50" class="form-control" placeholder="Имя">
                        </div>
                        <div class="form-group">
                            <input id="signupPassword" type="password" maxlength="25" class="form-control" placeholder="Пароль" length="40">
                        </div>
                        <div class="form-group">
                            <button id="signupSubmit" type="submit" class="btn btn-info btn-block">Логин</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>