<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <div class="panel panel-primary mt-5">
                <div class="panel-body">
                    <form method="POST" action="#" role="form">
                        <div class="form-group">
                            <h2>Логин</h2>
                        </div>
                        <div class="form-group">
                            <input id="signupName"
                                   name="username"
                                   type="text"
                                   maxlength="50"
                                   class="form-control <?=isset($errors['username']) ? 'is-invalid' : ''?>"
                                   placeholder="Имя">
                            <div class="invalid-feedback">
                                <?=isset($errors['username']) ? implode(',', $errors['username']) : ''?>
                            </div>
                        </div>
                        <div class="form-group">
                            <input id="signupPassword"
                                   name="password"
                                   type="password"
                                   maxlength="25"
                                   class="form-control <?=isset($errors['password']) ? 'is-invalid' : ''?>"
                                   placeholder="Пароль"
                                   length="40">
                            <div class="invalid-feedback">
                                <?=isset($errors['password']) ? implode(',', $errors['password']) : ''?>
                            </div>
                        </div>
                        <div class="form-group">
                            <button id="signupSubmit" type="submit" class="btn btn-info btn-block">Логин</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>