<?php
use App\Domain\User\User;
use App\Domain\Game\Game;
use App\Domain\Game\GameStatus;

$games = $data['games'];
$usersInGameIds = $data['usersInGameIds'];
$users = $data['users'];
?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-gamepad"></i> Games</h1>
</section>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Filter</h3>
        </div>
        <form class="form-horizontal" role="form">
            <div class="box-body">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Field 1</label>

                        <div class="col-sm-9">
                            <input class="form-control" id="inputEmail3" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-3 control-label">Field 2</label>

                        <div class="col-sm-9">
                            <input class="form-control" id="inputPassword3" type="text">
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-info">Search</button>
                <button type="submit" class="btn btn-default">Cancel</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>

    <!-- Default box -->
    <div class="box">
        <div class="box-body no-padding">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Status</th>
                        <th>Owner</th>
                        <th>Created date</th>
                        <th>Users</th>
                    </tr>
                </thead>
                <tbody>
                <?php /** @var Game $game */ ?>
                <?php foreach ($games as $game): ?>
                    <tr>
                        <td><?= $game->getId(); ?></td>
                        <td><?= GameStatus::getById($game->getStatus()); ?></td>
                        <td>
                            <?= "(#{$users[$game->getOwnerId()]->getId()}) {$users[$game->getOwnerId()]->getName()}" ?>
                        </td>
                        <td><?= $game->getCreatedDt(); ?></td>
                        <td>
                            <?php foreach ($usersInGameIds[$game->getId()] as $userId): ?>
                                <?= "(#{$users[$userId]->getId()}) {$users[$userId]->getName()}" ?><br/>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- pagination -->
        <?= $this->partial('block-admin::pagination')?>
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->