<!-- Content Header (Page header) -->
<section class="content-header">
    <h1><i class="fa fa-gamepad"></i> Games</h1>
</section>

<!-- Main content -->
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Filter</h3>
        </div>
        <form class="form-horizontal" role="form">
            <div class="box-body">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Field 1</label>

                        <div class="col-sm-9">
                            <input class="form-control" id="inputEmail3" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-3 control-label">Field 2</label>

                        <div class="col-sm-9">
                            <input class="form-control" id="inputPassword3" type="text">
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-info">Search</button>
                <button type="submit" class="btn btn-default">Cancel</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>

    <!-- Default box -->
    <div class="box">
        <div class="box-body no-padding">
            <table class="table">
                <tbody><tr>
                    <th style="width: 10px">#</th>
                    <th>Task</th>
                    <th>Progress</th>
                    <th style="width: 40px">Label</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Update software</td>
                    <td>
                        <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                        </div>
                    </td>
                    <td><span class="badge bg-red">55%</span></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Clean database</td>
                    <td>
                        <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-yellow" style="width: 70%"></div>
                        </div>
                    </td>
                    <td><span class="badge bg-yellow">70%</span></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Cron job running</td>
                    <td>
                        <div class="progress progress-xs progress-striped active">
                            <div class="progress-bar progress-bar-primary" style="width: 30%"></div>
                        </div>
                    </td>
                    <td><span class="badge bg-light-blue">30%</span></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Fix and squish bugs</td>
                    <td>
                        <div class="progress progress-xs progress-striped active">
                            <div class="progress-bar progress-bar-success" style="width: 90%"></div>
                        </div>
                    </td>
                    <td><span class="badge bg-green">90%</span></td>
                </tr>
                </tbody></table>
        </div>
        <!-- pagination -->
        <?= $this->partial('block-admin::pagination')?>
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->