<?php
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Princess Bubblegum game</title>
    <?php echo $this->headMeta(); ?>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/landing-page.min.css" rel="stylesheet">
    <?php echo $this->headLink(); ?>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="/zf-logo.png" alt="Zend Expressive" />
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="https://docs.zendframework.com/zend-expressive/" target="_blank">
                                <i class="fa fa-book"></i> Docs
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/zendframework/zend-expressive" target="_blank">
                                <i class="fa fa-wrench"></i> Contribute
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('api.ping') ?>">
                                Ping Test
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?php echo $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. All rights reserved.
            </p>
        </div>
    </footer>

    <?php echo $this->inlineScript(); ?>
</body>
</html>
