<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Princess Bubblegum game</title>
    <?php echo $this->headMeta(); ?>

    <!-- Bootstrap core CSS -->
    <link href="plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="plugins/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/landing-page.css" rel="stylesheet">
    <?php echo $this->headLink(); ?>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href="#">Princess Bubblegum</a>
            <a class="btn btn-primary" href="#">Играть</a>
        </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead text-white text-center">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-12 mx-auto">
                    <h2 class="mb-5">
                        Это быстрая и азартная карточная игра с элементами блефа, возможностью частично рассчитывать
                        действия противников и весомой долей везения.
                    </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                    <form>
                        <div class="form-row">
                            <div class="col-12 col-md-12">
                                <button type="submit" class="btn btn-block btn-lg btn-primary">Играть</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <!-- Testimonials -->
    <section class="testimonials text-center bg-light" style="background-color: #a0ceb2 !important;">
        <div class="container">
            <h2 class="mb-5">What people are saying...</h2>
            <div class="row">
                <div class="col-lg-4">
                    <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                        <img class="img-fluid rounded-circle mb-3" src="img/win-1.jpg" alt="">
                        <h5>Рейтинги</h5>
                        <p class="font-weight-light mb-0">Выигрывай, стань лучшим</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                        <img class="img-fluid rounded-circle mb-3" src="img/win-2.jpg" alt="">
                        <h5>Матчи</h5>
                        <p class="font-weight-light mb-0">Еженедельные матчи с приятными призами</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                        <img class="img-fluid rounded-circle mb-3" src="img/win-3.jpg" alt="">
                        <h5>Квесты</h5>
                        <p class="font-weight-light mb-0">Играй каждый день и получай бонусы</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Image Showcases -->
    <section class="showcase">
        <div class="container-fluid p-0">
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.png');"></div>
                <div class="col-lg-6 order-lg-1 my-auto showcase-text text-al text-right">
                    <h2>1 - Парнишка Финн</h2>
                    <p class="lead mb-0">Назови карту от 2 до 8, выбери игрока,<br/>
                        если у него есть названная карта он<br/>
                        выбывает из раунда</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-2.png');"></div>
                <div class="col-lg-6 my-auto showcase-text">
                    <h2>2 - Пес Джейк</h2>
                    <p class="lead mb-0">Посмотри карут на руке у другого игрока</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-3.png');"></div>
                <div class="col-lg-6 order-lg-1 my-auto showcase-text text-right">
                    <h2>3 - БиМо</h2>
                    <p class="lead mb-0">В тайне от остальных сравни свою руку <br/>
                        с рукой другого игрока. У кого значение меньше, <br/>
                        тот выбывает из раунда</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-4.png');"></div>
                <div class="col-lg-6 my-auto showcase-text">
                    <h2>4 - ППК</h2>
                    <p class="lead mb-0">До следующего твоего хода <br/>
                        игнорируй все эффекты карт других игроков</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-5.png');"></div>
                <div class="col-lg-6 order-lg-1 my-auto showcase-text text-right">
                    <h2>5 - Маршал Ли</h2>
                    <p class="lead mb-0">Выбери другого игрока (можно себя) <br/>
                        этот игрок сбрасывает карту с руки и берет новую</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-6.png');"></div>
                <div class="col-lg-6 my-auto showcase-text">
                    <h2>6 - Ледяной король</h2>
                    <p class="lead mb-0">Поменяйся картой с руки с другим, <br/>
                        выбранным тобою, игроком </p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-7.png');"></div>
                <div class="col-lg-6 order-lg-1 my-auto showcase-text text-right">
                    <h2>7 - Марселина</h2>
                    <p class="lead mb-0">Если эта карта у тебя на руке одоновременно<br/>
                        с Ледяным королем или Маршалом Ли<br/>
                        ты должен сбросить ее</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-showcase-8.png');"></div>
                <div class="col-lg-6 my-auto showcase-text">
                    <h2>8 - Принцесса жвачка</h2>
                    <p class="lead mb-0">Если сбросишь эту карту, тут же выбываешь из раунда</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <h2 class="mb-4">Готов?</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto">
                    <form>
                        <div class="form-row">
                            <div class="col-12 col-md-12">
                                <button type="submit" class="btn btn-block btn-lg btn-primary">Играть</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item">
                            <a href="#">About</a>
                        </li>
                        <li class="list-inline-item">&sdot;</li>
                        <li class="list-inline-item">
                            <a href="#">Contact</a>
                        </li>
                        <li class="list-inline-item">&sdot;</li>
                        <li class="list-inline-item">
                            <a href="#">Terms of Use</a>
                        </li>
                        <li class="list-inline-item">&sdot;</li>
                        <li class="list-inline-item">
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; pbblg.com <?=date('Y') ?>. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item mr-3">
                            <a href="#">
                                <i class="fa fa-facebook fa-2x fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item mr-3">
                            <a href="#">
                                <i class="fa fa-twitter fa-2x fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fa fa-instagram fa-2x fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <?php echo $this->inlineScript(); ?>
</body>
</html>
